version: '3'

services:
  hub:
    build:
      context: ./hub
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: 5.2 # latest
    image: jupyterhub
    container_name: jupyterhub
    # command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --debug
    environment:
      - LOCAL_VOLUME=${LOCAL_VOLUME}
    ports: 
      - 8000:8000
    volumes:
      - ./hub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    networks:
      - jupyter-network

networks:
  jupyter-network:
    name: jupyter-network
