# FROM quay.io/jupyter/docker-stacks-foundation:latest
FROM quay.io/jupyter/base-notebook:2024-12-29

USER root

RUN apt update && apt install apt-transport-https ca-certificates curl gnupg ffmpeg libsm6 libxext6 vim neovim htop -y

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
    apt update -y && \
    apt install google-cloud-cli-anthoscli -y

RUN pip install --upgrade pip

RUN conda install cmake=3.29.6

# Install
RUN pip install \
    pyyaml==6.0.2 \
    tqdm==4.66.4 \
    requests==2.32.3 \
    easydict==1.13 \
    prettytable==3.10.0 \
    numpy==1.26.4 \
    pandas==2.2.2 \
    polars==0.20.31 \
    matplotlib==3.9.0 \
    plotly==5.22.0 \
    seaborn==0.13.2 \
    Pillow==10.3.0 \
    opencv-python==4.10.0.84 \
    scikit-image==0.24.0 \
    imutils==0.5.4 \
    scikit-learn==1.5.0 \
    optuna==3.6.1 \
    shap==0.45.1

RUN pip install \
    xgboost==2.1.0 \
    lightgbm==4.4.0 \
    catboost==1.2.5
 
RUN pip install \
    tensorflow==2.16.2 \
    torch==2.3.1 \
    torchaudio==2.3.1 \
    torchvision==0.18.1 \
    efficientnet==1.1.1 \
    onnx==1.16.1 \
    onnxruntime==1.18.0 \
    tf2onnx==1.16.1 \
    skl2onnx==1.17.0

USER jovyan
